"""
SkinTextureGenerator.py
Adds skin texture percentage columns to synthetic skin tone profiles
using Dirichlet distribution for realistic composition modeling
"""

import numpy as np
import pandas as pd
import os

# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────
INPUT_FILE = "output/synthetic_skin_tones.csv"
OUTPUT_DIR = "output"
OUTPUT_FILE = "skin_profiles_with_texture.csv"
RANDOM_STATE = 42

# Dirichlet concentration parameters
# [normal, oily, dry] - higher values = more concentration
ALPHA = [3.0, 2.0, 2.0]

# Validation tolerance
SUM_TOLERANCE = 0.01


def load_skin_tones(filepath=INPUT_FILE):
    """
    Load the skin tone profiles generated by SkinToneGenerator.py
    
    Args:
        filepath: Path to the input CSV file
    
    Returns:
        pandas DataFrame with L, a, b, MST_Class, Undertone columns
    """
    if not os.path.exists(filepath):
        print(f"ERROR: File not found: {filepath}")
        print("Please run SkinToneGenerator.py first!")
        return None
    
    df = pd.read_csv(filepath)
    print(f"Loaded {len(df)} skin tone profiles from {filepath}")
    print(f"Columns: {df.columns.tolist()}")
    
    return df


def generate_texture_percentages(n_samples, alpha=ALPHA, random_state=RANDOM_STATE):
    """
    Generate texture percentage compositions using Dirichlet distribution
    
    Args:
        n_samples: Number of samples to generate
        alpha: Concentration parameters [normal, oily, dry]
        random_state: Random seed for reproducibility
    
    Returns:
        pandas DataFrame with normal_pct, oily_pct, dry_pct columns
    """
    print(f"\nGenerating texture percentages using Dirichlet distribution...")
    print(f"Alpha parameters: {alpha} (normal, oily, dry)")
    
    np.random.seed(random_state)
    
    # Generate compositions that sum to 1.0
    compositions = np.random.dirichlet(alpha, size=n_samples)
    
    # Convert to percentages
    percentages = compositions * 100
    
    # Round all but the first column to 2 decimal places
    percentages[:, 1] = np.round(percentages[:, 1], 2)
    percentages[:, 2] = np.round(percentages[:, 2], 2)
    
    # Calculate the first column to ensure sum = 100.0
    percentages[:, 0] = 100.0 - percentages[:, 1] - percentages[:, 2]
    
    # Round the first column to 2 decimal places
    percentages[:, 0] = np.round(percentages[:, 0], 2)
    
    # Create DataFrame
    texture_df = pd.DataFrame({
        'normal_pct': percentages[:, 0],
        'oily_pct': percentages[:, 1],
        'dry_pct': percentages[:, 2]
    })
    
    print(f"Generated {len(texture_df)} texture compositions")
    
    return texture_df


def validate_textures(df):
    """
    Validate that texture percentages meet all constraints
    
    Args:
        df: DataFrame with normal_pct, oily_pct, dry_pct columns
    
    Returns:
        bool: True if all validations pass
    """
    print("\n" + "=" * 70)
    print("TEXTURE VALIDATION")
    print("=" * 70)
    
    all_valid = True
    
    # Check 1: Sum to 100
    row_sums = df['normal_pct'] + df['oily_pct'] + df['dry_pct']
    sum_violations = np.abs(row_sums - 100.0) > SUM_TOLERANCE
    
    if sum_violations.any():
        n_violations = sum_violations.sum()
        print(f"[WARNING] {n_violations} rows do not sum to 100.0 (tolerance: {SUM_TOLERANCE})")
        print(f"Example violations:")
        print(df[sum_violations][['normal_pct', 'oily_pct', 'dry_pct']].head())
        all_valid = False
    else:
        print(f"PASS - All rows sum to 100.0 (tolerance: {SUM_TOLERANCE})")
    
    # Check 2: No negative values
    negative_mask = (df['normal_pct'] < 0) | (df['oily_pct'] < 0) | (df['dry_pct'] < 0)
    if negative_mask.any():
        n_negative = negative_mask.sum()
        print(f"[WARNING] {n_negative} rows contain negative values")
        all_valid = False
    else:
        print(f"PASS - No negative values found")
    
    # Check 3: No values exceed 100
    exceed_mask = (df['normal_pct'] > 100) | (df['oily_pct'] > 100) | (df['dry_pct'] > 100)
    if exceed_mask.any():
        n_exceed = exceed_mask.sum()
        print(f"[WARNING] {n_exceed} rows contain values exceeding 100")
        all_valid = False
    else:
        print(f"PASS - No values exceed 100")
    
    # Summary statistics
    print("\n" + "=" * 70)
    print("TEXTURE PERCENTAGE STATISTICS")
    print("=" * 70)
    
    for col in ['normal_pct', 'oily_pct', 'dry_pct']:
        print(f"\n{col}:")
        print(f"  Mean: {df[col].mean():.2f}")
        print(f"  Std:  {df[col].std():.2f}")
        print(f"  Min:  {df[col].min():.2f}")
        print(f"  Max:  {df[col].max():.2f}")
    
    return all_valid


def save_dataset(df, output_dir=OUTPUT_DIR, filename=OUTPUT_FILE):
    """
    Save the enriched dataset with texture percentages
    
    Args:
        df: DataFrame with all columns
        output_dir: Directory to save the file
        filename: Output filename
    """
    filepath = os.path.join(output_dir, filename)
    df.to_csv(filepath, index=False)
    print(f"\nDataset saved: {filepath}")
    print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
    return filepath


def main():
    """Main execution function"""
    print("=" * 70)
    print("SKIN TEXTURE GENERATOR - Dirichlet-based Composition Modeling")
    print("=" * 70)
    
    # Ensure output directory exists
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
    
    # Step 1: Load skin tone data
    print("\n[STEP 1] Loading Skin Tone Profiles...")
    df = load_skin_tones()
    if df is None:
        return
    
    # Step 2: Generate texture percentages
    print("\n[STEP 2] Generating Texture Percentages...")
    texture_df = generate_texture_percentages(len(df), alpha=ALPHA, random_state=RANDOM_STATE)
    
    # Combine with original data
    df = pd.concat([df, texture_df], axis=1)
    
    # Step 3: Validate textures
    print("\n[STEP 3] Validating Texture Compositions...")
    is_valid = validate_textures(df)
    
    if not is_valid:
        print("\n[WARNING] Validation issues detected. Review output above.")
    
    # Step 4: Show sample data
    print("\n[STEP 4] Sample Data (first 10 rows):")
    display_cols = ['L', 'a', 'b', 'MST_Class', 'Undertone', 
                   'normal_pct', 'oily_pct', 'dry_pct']
    print(df[display_cols].head(10).to_string(index=False))
    
    # Step 5: Save dataset
    print("\n[STEP 5] Saving Enriched Dataset...")
    save_dataset(df, OUTPUT_DIR)
    
    print("\n" + "=" * 70)
    print("TEXTURE GENERATION COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()
